### ISSUE TITLE
Alignment problem using Linux Screen 

### ISSUE THREAD

**Issue by fxyu** [inducer/pudb#393] opened 2020-07-14 11:30 UTC
I'm new to ```pudb```  and I really like the interface.
I am currently trying to use ```pudb``` under Linux ```screen``` and the alignment is not what I expected.

<img width="1233" alt="pudb_bug" src="https://user-images.githubusercontent.com/15837932/87420578-202bc980-c608-11ea-8824-ed5c4e3a69c4.png">

There is no issue when I use it without using Linux ```screen``` and I also found that it is terminal specific. I have no issue when using "cmder" in Windows10 but this problem occur when I use "Hyper" and "Terminus" under Linux ```screen```.

**Comment by inducer** [comment] 2020-07-14 20:53
Just tried on Debian testing with screen 4.8.0 on [kitty](https://github.com/kovidgoyal/kitty)0.18.1 and gnome-terminal 3.36.2 (libvte 0.60.3). I'm not able to reproduce the issue.

What do you observe the environment variable `$TERM` to be set to inside screen? What version do you use? Does the issue occur when using [tmux](https://github.com/tmux/tmux/) (I use that nearly daily with pudb and have never had an issue.)

**Comment by asmeurer** [comment] 2020-07-14 23:49
Looks like it's probably an urwid problem. What version of urwid do you have?

**Comment by fxyu** [comment] 2020-07-15 12:23
> Just tried on Debian testing with screen 4.8.0 on [kitty](https://github.com/kovidgoyal/kitty) 0.18.1 and gnome-terminal 3.36.2 (libvte 0.60.3). I'm not able to reproduce the issue.
> 
> What do you observe the environment variable `$TERM` to be set to inside screen? What version do you use? Does the issue occur when using [tmux](https://github.com/tmux/tmux/) (I use that nearly daily with pudb and have never had an issue.)

without using the screen ```echo $TERM``` returns ```screen-256color```
when inside a screen ```echo $TERM``` returns ```screen```

The version of the screen is **version 4.03.01 (GNU) 28-Jun-15**
I try to install tmux to test this issue.



> Looks like it's probably an urwid problem. What version of urwid do you have?
my urwid version is 2.1.0

**Comment by inducer** [comment] 2020-07-15 15:49
What happens when you run one of the [urwid sample apps](https://github.com/urwid/urwid/tree/master/examples)?

**Comment by fxyu** [comment] 2020-07-18 07:27
Some similar problem occur when I ran urwid sample apps.

![image](https://user-images.githubusercontent.com/15837932/87847458-20c7a700-c90b-11ea-9fbd-4aff6e2113f5.png)

**Comment by inducer** [comment] 2020-07-18 19:03
Hmm... that points to a problem that should be addressed by fixing Urwid then. It's not likely that pudb can do much about that. Have you tried switching to the `curses` display driver in pudb?

**Comment by fxyu** [comment] 2020-07-22 18:00
I use WSL in windows as the shell and it fixed the problem. Which $TERM is prefer for using pudb?

**Comment by inducer** [comment] 2020-07-22 19:15
It's not really a choice. `$TERM` should match your terminfo database and the terminal you're using. Some examples that work on my system: `xterm`, `xterm-kitty`, `screen`.

**Closed** 2020-07-24 17:00 UTC

**Comment by asmeurer** [comment] 2020-07-24 19:10
Did you fix the problem by modifying your $TERM environment variable or by changing the display driver in the pudb settings?

**Comment by fxyu** [comment] 2020-08-02 10:07
I've moved to use tmux as my screen mutiplxer, and I fixed my $TERM env variable to ```screen-256color```. It fixed the problem.
