### ISSUE TITLE
Changing variable value while debugging

### ISSUE THREAD

**Issue by catoleg** [inducer/pudb#314] opened 2018-09-21 19:09 UTC
There is impossible to set a new value to the existing variable while debugging.

I tried to set in the 'Command line' window, debugger allows it but the value is not set:
>>> port
3
>>>port = 10
>>>port
3 

Also tried to set it via external shell. In that case variable seams to be changed, but debugger ignores that new value, and continue to work with old value:
>>> port = 30
>>> port
30

Also tried to set the the value to the variable through the 'Variables' windows, but it returns an error:
port = 10: <error>

It would be very useful to have such feature. Thank you for attention.

**Comment by inducer** [comment] 2018-09-22 00:59
Dupe of #26.

**Closed by inducer** 2018-09-22 00:59 UTC
