### ISSUE TITLE
sort variables by the order at which they are update/added

### ISSUE THREAD

**Issue by w-hc** [inducer/pudb#307] opened 2018-08-07 03:05 UTC
When a stack involves lots of local variables, it would be nice to view them based on the order at which they are added or updated. This is usually the logical order that is most natural to the user. Sorting them alphabetically is not the most helpful way to display them and usually scatter important bits all over the places.  

In fact, I would suggest using the update order as the default rather than alphabetical order.

**Comment by asmeurer** [comment] 2018-08-07 03:14
Dupe of https://github.com/inducer/pudb/issues/107. The question is how to actually implement this.

**Closed by asmeurer** 2018-08-07 03:14 UTC
