### ISSUE TITLE
NotImplementedError: `Instances` object is not iterable! 

### ISSUE THREAD

**Issue by 9p15p** [inducer/pudb#516] opened 2022-05-20 09:41 UTC
**Describe the bug**

**To Reproduce**
when I Use pudb in Detectron2 and want to expand the Variable, the error happens.
It seems some classes can not be enumerated.

```
python version: 3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
pudb version: 2022.1.1
urwid version: 2.1.2
Traceback (most recent call last):
  File "/root/conda/lib/python3.7/site-packages/pudb/debugger.py", line 2673, in event_loop
    toplevel.keypress(self.size, k)
  File "/root/conda/lib/python3.7/site-packages/pudb/ui_tools.py", line 119, in keypress
    result = self._w.keypress(size, key)
  File "/root/conda/lib/python3.7/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/root/conda/lib/python3.7/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/root/conda/lib/python3.7/site-packages/pudb/ui_tools.py", line 119, in keypress
    result = self._w.keypress(size, key)
  File "/root/conda/lib/python3.7/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/root/conda/lib/python3.7/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/root/conda/lib/python3.7/site-packages/pudb/ui_tools.py", line 124, in keypress
    return handler(self, size, key)
  File "/root/conda/lib/python3.7/site-packages/pudb/debugger.py", line 998, in change_var_state
    self.update_var_view(focus_index=focus_index)
  File "/root/conda/lib/python3.7/site-packages/pudb/debugger.py", line 2753, in update_var_view
    locals, globals)
  File "/root/conda/lib/python3.7/site-packages/pudb/var_view.py", line 737, in make_var_view
    tmv_walker.walk_value(None, var, locals[var])
  File "/root/conda/lib/python3.7/site-packages/pudb/var_view.py", line 620, in walk_value
    self.walk_container(new_parent_item, label, value, id_path)
  File "/root/conda/lib/python3.7/site-packages/pudb/var_view.py", line 557, in walk_container
    entry, entry_id_path)
  File "/root/conda/lib/python3.7/site-packages/pudb/var_view.py", line 620, in walk_value
    self.walk_container(new_parent_item, label, value, id_path)
  File "/root/conda/lib/python3.7/site-packages/pudb/var_view.py", line 544, in walk_container
    container_cls.entries(value, label)):
  File "/root/conda/lib/python3.7/site-packages/pudb/var_view.py", line 104, in entries
    for count, entry in enumerate(sequence):
  File "/root/conda/lib/python3.7/site-packages/detectron2/structures/instances.py", line 143, in __iter__
    raise NotImplementedError("`Instances` object is not iterable!")
NotImplementedError: `Instances` object is not iterable!
```

**Expected behavior**

**Screenshots**

**Additional context**

**Versions**
pudb==2022.1.1 python=3.7.7
What version of pudb? What version of Python?

**Comment by inducer** [comment] 2022-05-20 14:19
The information here does not suffice to reproduce the bug. Closing.

**Comment by mvanderkamp** [comment] 2022-05-20 20:29
I think I see what happened here: this class implements the `__iter__` method, but the implementation only raises a `NotImplementedError`. I think this could reasonably be classified as a user error with no action from us required. The easy alternative is to change the `except` clause in our container ABCs with a general `except Exception` since who knows what users are doing in their code.

**Closed** 2022-05-20 21:07 UTC
Labels: Bug

**Comment by 9p15p** [comment] 2022-05-21 05:54
Thank you！
