### ISSUE TITLE
Local variable changes not saved, only global variables can be changed.

### ISSUE THREAD

**Issue by kgabor** [inducer/pudb#332] opened 2019-04-05 05:36 UTC
If new values are assigned to global variables in the command line while the code is stopped, they are correctly set for the continued execution. Local variables however seems to be lost immediately. In this example, `b` can be changed, `x` however cannot by pudb.

Python version: 3.6.6
```
b = 10
def f():
        x = 1
        return x

print(f())
print(b)
```
Breaking at line 4:

```
>>> x                                                                                     
1                                                                                         
>>> x = 2                                                                                 
>>> x                                                                                     
1                                                                                         
```
and f() returns 1.

This issue may be related to [this older pdb problem](https://stackoverflow.com/questions/7912820/how-do-i-change-a-value-while-debugging-python-with-pdb).

**Comment by inducer** [comment] 2019-04-05 14:59
Dupe of #26.

**Closed by inducer** 2019-04-05 14:59 UTC
